export enum Currency {
    AED = "AED",
    AFN = "AFN",
    ALL = "ALL",
    AMD = "AMD",
    ANG = "ANG",
    AOA = "AOA",
    ARS = "ARS",
    AUD = "AUD",
    AWG = "AWG",
    AZN = "AZN",
    BAM = "BAM",
    BBD = "BBD",
    BDT = "BDT",
    BGN = "BGN",
    BHD = "BHD",
    BIF = "BIF",
    BMD = "BMD",
    BND = "BND",
    BOB = "BOB",
    BRL = "BRL",
    BSD = "BSD",
    BTN = "BTN",
    BWP = "BWP",
    BZD = "BZD",
    CAD = "CAD",
    CDF = "CDF",
    CHF = "CHF",
    CLF = "CLF",
    CLP = "CLP",
    CNH = "CNH",
    CNY = "CNY",
    COP = "COP",
    CUP = "CUP",
    CVE = "CVE",
    CZK = "CZK",
    DJF = "DJF",
    DKK = "DKK",
    DOP = "DOP",
    DZD = "DZD",
    EGP = "EGP",
    ERN = "ERN",
    ETB = "ETB",
    EUR = "EUR",
    FJD = "FJD",
    FKP = "FKP",
    GBP = "GBP",
    GEL = "GEL",
    GHS = "GHS",
    GIP = "GIP",
    GMD = "GMD",
    GNF = "GNF",
    GTQ = "GTQ",
    GYD = "GYD",
    HKD = "HKD",
    HNL = "HNL",
    HRK = "HRK",
    HTG = "HTG",
    HUF = "HUF",
    IDR = "IDR",
    ILS = "ILS",
    INR = "INR",
    IQD = "IQD",
    IRR = "IRR",
    ISK = "ISK",
    JMD = "JMD",
    JOD = "JOD",
    JPY = "JPY",
    KES = "KES",
    KGS = "KGS",
    KHR = "KHR",
    KMF = "KMF",
    KPW = "KPW",
    KRW = "KRW",
    KWD = "KWD",
    KYD = "KYD",
    KZT = "KZT",
    LAK = "LAK",
    LBP = "LBP",
    LKR = "LKR",
    LRD = "LRD",
    LSL = "LSL",
    LYD = "LYD",
    MAD = "MAD",
    MDL = "MDL",
    MGA = "MGA",
    MKD = "MKD",
    MMK = "MMK",
    MNT = "MNT",
    MOP = "MOP",
    MRU = "MRU",
    MUR = "MUR",
    MVR = "MVR",
    MWK = "MWK",
    MXN = "MXN",
    MYR = "MYR",
    MZN = "MZN",
    NAD = "NAD",
    NGN = "NGN",
    NOK = "NOK",
    NPR = "NPR",
    NZD = "NZD",
    OMR = "OMR",
    PAB = "PAB",
    PEN = "PEN",
    PGK = "PGK",
    PHP = "PHP",
    PKR = "PKR",
    PLN = "PLN",
    PYG = "PYG",
    QAR = "QAR",
    RON = "RON",
    RSD = "RSD",
    RUB = "RUB",
    RWF = "RWF",
    SAR = "SAR",
    SCR = "SCR",
    SDG = "SDG",
    SEK = "SEK",
    SGD = "SGD",
    SHP = "SHP",
    SLL = "SLL",
    SOS = "SOS",
    SRD = "SRD",
    SYP = "SYP",
    SZL = "SZL",
    THP = "THB",
    TJS = "TJS",
    TMT = "TMT",
    TND = "TND",
    TOP = "TOP",
    TRY = "TRY",
    TTD = "TTD",
    TWD = "TWD",
    TZS = "TZS",
    UAH = "UAH",
    UGX = "UGX",
    USD = "USD",
    UYU = "UYU",
    UZS = "UZS",
    VND = "VND",
    VUV = "VUV",
    WST = "WST",
    XAF = "XAF",
    XCD = "XCD",
    XDR = "XDR",
    XOF = "XOF",
    XPE = "XPF",
    YER = "YER",
    ZAR = "ZAR",
    ZMW = "ZMW"
}

export const ListCurrency = [
    { name :"AED" },
    { name :"AFN" },
    { name :"ALL" },
    { name :"AMD" },
    { name :"ANG" },
    { name :"AOA" },
    { name :"ARS" },
    { name :"AUD" },
    { name :"AWG" },
    { name :"AZN" },
    { name :"BAM" },
    { name :"BBD" },
    { name :"BDT" },
    { name :"BGN" },
    { name :"BHD" },
    { name :"BIF" },
    { name :"BMD" },
    { name :"BND" },
    { name :"BOB" },
    { name :"BRL" },
    { name :"BSD" },
    { name :"BTN" },
    { name :"BWP" },
    { name :"BZD" },
    { name :"CAD" },
    { name :"CDF" },
    { name :"CHF" },
    { name :"CLF" },
    { name :"CLP" },
    { name :"CNH" },
    { name :"CNY" },
    { name :"COP" },
    { name :"CUP" },
    { name :"CVE" },
    { name :"CZK" },
    { name :"DJF" },
    { name :"DKK" },
    { name :"DOP" },
    { name :"DZD" },
    { name :"EGP" },
    { name :"ERN" },
    { name :"ETB" },
    { name :"EUR" },
    { name :"FJD" },
    { name :"FKP" },
    { name :"GBP" },
    { name :"GEL" },
    { name :"GHS" },
    { name :"GIP" },
    { name :"GMD" },
    { name :"GNF" },
    { name :"GTQ" },
    { name :"GYD" },
    { name :"HKD" },
    { name :"HNL" },
    { name :"HRK" },
    { name :"HTG" },
    { name :"HUF" },
    { name :"IDR" },
    { name :"ILS" },
    { name :"INR" },
    { name :"IQD" },
    { name :"IRR" },
    { name :"ISK" },
    { name :"JMD" },
    { name :"JOD" },
    { name :"JPY" },
    { name :"KES" },
    { name :"KGS" },
    { name :"KHR" },
    { name :"KMF" },
    { name :"KPW" },
    { name :"KRW" },
    { name :"KWD" },
    { name :"KYD" },
    { name :"KZT" },
    { name :"LAK" },
    { name :"LBP" },
    { name :"LKR" },
    { name :"LRD" },
    { name :"LSL" },
    { name :"LYD" },
    { name :"MAD" },
    { name :"MDL" },
    { name :"MGA" },
    { name :"MKD" },
    { name :"MMK" },
    { name :"MNT" },
    { name :"MOP" },
    { name :"MRU" },
    { name :"MUR" },
    { name :"MVR" },
    { name :"MWK" },
    { name :"MXN" },
    { name :"MYR" },
    { name :"MZN" },
    { name :"NAD" },
    { name :"NGN" },
    { name :"NOK" },
    { name :"NPR" },
    { name :"NZD" },
    { name :"OMR" },
    { name :"PAB" },
    { name :"PEN" },
    { name :"PGK" },
    { name :"PHP" },
    { name :"PKR" },
    { name :"PLN" },
    { name :"PYG" },
    { name :"QAR" },
    { name :"RON" },
    { name :"RSD" },
    { name :"RUB" },
    { name :"RWF" },
    { name :"SAR" },
    { name :"SCR" },
    { name :"SDG" },
    { name :"SEK" },
    { name :"SGD" },
    { name :"SHP" },
    { name :"SLL" },
    { name :"SOS" },
    { name :"SRD" },
    { name :"SYP" },
    { name :"SZL" },
    { name :"THB" },
    { name :"TJS" },
    { name :"TMT" },
    { name :"TND" },
    { name :"TOP" },
    { name :"TRY" },
    { name :"TTD" },
    { name :"TWD" },
    { name :"TZS" },
    { name :"UAH" },
    { name :"UGX" },
    { name :"USD" },
    { name :"UYU" },
    { name :"UZS" },
    { name :"VND" },
    { name :"VUV" },
    { name :"WST" },
    { name :"XAF" },
    { name :"XCD" },
    { name :"XDR" },
    { name :"XOF" },
    { name :"XPF" },
    { name :"YER" },
    { name :"ZAR" },
    { name :"ZMW" }
]
